### ISSUE TITLE
Bug: Removed/renamed devices are not removed

### ISSUE THREAD

**Issue by rasssta** [rickardp/homey-prometheus-exporter#3]
When deleting and/or renaming a device, the old device/name will still remain in the /metrics data with its last reported value until the Homey is rebooted.

**Comment by rasssta** [comment]
Restarting the app also solves the issue

**Comment by klippo** [comment]
This would explain why I still have devices that was renamed.

Looking through source it looks like updateDeviceList() is only called onInit()

**Comment by rickardp** [comment]
Thanks for reporting. Yes, that is one of the side effects of adding name and zone to the label.

Actually, device changes such as renames are subscribed to (otherwise new devices or new names wouldn’t be picked up). The problem is that the client library keeps a list of all the labels already reported (until it is restarted).

I think it could be investigated if it is possible to remove label values.

The next step for the user would then be to migrate or prune the obsolete data from Prometheus.

**Comment by klippo** [comment]
Would it be possible to compare devicelists and use Gauge.reset() when something is removed?

**Comment by rickardp** [comment]
reset() is not a good idea as the labels will only get new values after an update in that particular value. The proper way would be to remove the specific labels that are gone by comparing the key sets. I haven’t seen such an api within prom-client though, but maybe it’s possible.

Note that stale metrics take no space and thus I consider this to be quite low prio to fix, but please let me know if you disagree (preferably with the use case that you have).

**Comment by rickardp** [comment]
After giving it a second thought, reset() is already called now, to solve the issues with devices that have changed zones. The device is explicitly polled to solve the "hole" issue (at the expense of making the refresh more costly).
